version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: packman-app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - packman-net

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: packman
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - packman-net

volumes:
  db_data:

networks:
  packman-net:
    driver: bridge
